# Generated by Django 3.1.7 on 2021-03-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('floor', models.DecimalField(decimal_places=0, max_digits=2)),
                ('localNum', models.DecimalField(decimal_places=0, max_digits=4)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('webpage', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(max_length=100)),
                ('logo', models.ImageField(default='img/logos/default.png', upload_to='img/logos')),
                ('localFoto', models.ImageField(default='img/locals/logolocal.png', upload_to='img/locals')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False, null=True)),
                ('outstanding', models.BooleanField(blank=True, default=True)),
                ('pay', models.CharField(choices=[('unmes', 'Mes'), ('tresmes', 'Trimestre'), ('seismes', 'Semestre'), ('year', 'Anual')], default='En Aprobación', max_length=50)),
                ('payday', models.DateField()),
                ('activethru', models.DateField(blank=True)),
            ],
        ),
    ]
