# Generated by Django 3.1.7 on 2021-03-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210324_1213'),
        ('locals', '0002_local'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Localx',
        ),
    ]
