# Generated by Django 3.1.7 on 2021-04-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locals', '0003_delete_localx'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='ammont',
            field=models.CharField(default='20000', max_length=10),
        ),
        migrations.AddField(
            model_name='local',
            name='person',
            field=models.CharField(default='gabriel', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='local',
            name='pay',
            field=models.CharField(choices=[('unmes', 'Mes'), ('tresmes', 'Trimestre'), ('seismes', 'Semestre'), ('year', 'Anual')], default='En Aprobación', max_length=15),
        ),
        migrations.AlterField(
            model_name='local',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
