# Generated by Django 3.1.7 on 2021-04-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locals', '0004_auto_20210407_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='ammont',
            new_name='amount',
        ),
    ]
