# Generated by Django 3.1.7 on 2021-05-11 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locals', '0007_auto_20210408_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='payday',
            new_name='lastPay',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='outstanding',
            new_name='outstand',
        ),
        migrations.RemoveField(
            model_name='local',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='local',
            name='pay',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payday', models.DateField()),
                ('monts', models.DecimalField(decimal_places=0, default=1, max_digits=2)),
                ('amount', models.CharField(default='20000', max_length=10)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locals.local')),
            ],
        ),
    ]
