# Generated by Django 3.1.7 on 2021-05-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locals', '0008_auto_20210511_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
