# Generated by Django 3.1.7 on 2021-03-02 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, choices=[('Usado', 'Usado'), ('Nuevo', 'Nuevo')], default='En Aprobación', max_length=50, null=True)),
                ('category', models.CharField(blank=True, choices=[('Computadores', 'Computadores'), ('Celulares', 'Celulares'), ('Accesorios', 'Accesorios'), ('Gamers', 'Gamers'), ('Impresoras', 'Impresoras'), ('Audiovisual', 'Audiovisual'), ('Servicios', 'Servicios'), ('Alimentos', 'Alimentos')], default='En Aprobación', max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('foto1', models.ImageField(default='img/products/default.png', upload_to='img/products')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='img/products')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='img/products')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locals.localx')),
            ],
        ),
    ]
