# Generated by Django 3.1.7 on 2021-04-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210324_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Computadores', 'Computadores'), ('Celulares', 'Celulares'), ('Accesorios', 'Accesorios'), ('Gamers', 'Gamers'), ('Impresoras', 'Impresoras'), ('Audiovisual', 'Audiovisual'), ('Servicios', 'Servicios'), ('Alimentos', 'Alimentos')], default='Computadores', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('Usado', 'Usado'), ('Nuevo', 'Nuevo')], default='Nuevo', max_length=50, null=True),
        ),
    ]
