# Generated by Django 3.1.7 on 2021-05-11 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locals', '0008_auto_20210511_1625'),
        ('products', '0003_auto_20210423_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locals.local'),
        ),
    ]
