# Generated by Django 3.1.7 on 2021-05-15 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locals', '0009_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payday', models.DateField()),
                ('monts', models.DecimalField(decimal_places=0, default=1, max_digits=2)),
                ('amount', models.CharField(default='20000', max_length=10)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locals.local')),
            ],
        ),
    ]
